# Makefile for compiling fortran programs with automatic dependency
# generation and recognition of programs. Full support for parallel make.
#
# Object files are stored in $(OBJDIR)=.obj/
# Module files are stored in $(MODDIR)=.mod/
# Dependencies are stored in $(DEPDIR)=.dep/
#
# Known limitations:
# - Module/function/subroutine name must be equal to file name

# Include jorek-specific things and settings
include Makefile.inc
MODEL_NUMBER := $(subst model,,$(MODEL))
# Default rule needs to be first
main: jorek_model$(MODEL_NUMBER)

# Some defaults and parsing logic for makefile.inc
include defaults.mk

$(MODDIR):
	mkdir -p $(MODDIR)

$(MODDIR)/libmuscle.mod: | $(MODDIR)
	cp $(MUSCLE3_DIR)/libmuscle/fortran/build/libmuscle/libmuscle.mod $(MODDIR)/

$(MODDIR)/ymmsl.mod: | $(MODDIR)
	cp $(MUSCLE3_DIR)/libmuscle/fortran/build/libmuscle/ymmsl.mod $(MODDIR)/ 2>/dev/null || \
	find $(MUSCLE3_DIR) -name "ymmsl.mod" -exec cp {} $(MODDIR)/ \;

.mod/libmuscle.mod: ;
.mod/ymmsl.mod: ;

# Prevent make from trying to build libmuscle.o or ymmsl.o from source
$(OBJDIR)/libmuscle.o: ;
$(OBJDIR)/ymmsl.o: ;

# All object files depend on the external mods being present first
$(OBJDIR)/mod_com_dream.o: $(MODDIR)/libmuscle.mod $(MODDIR)/ymmsl.mod

# Build the main executable with a different name from the source file jorek2_main.o
jorek_model$(MODEL_NUMBER): $(OBJDIR)/jorek2_main.o $(shell ./util/obj_deps $(DEPDIR)/jorek2_main.d)
	$(FC) $(FLAGS) $(DEFINES) $(INCLUDES) -o $@ $^ $(LIBS)


.PHONY: clean cleanall cleandep duplicates
cleanall: clean cleandep
clean:
	@echo ">> Deleting Object Files <<"
	-@rm -r $(OBJDIR)
	@echo ">> Deleting Module Files <<"
	-@rm -r $(MODDIR)
	-@find . -name '*.mod' -delete -or -name '*.o' -delete
	-@rm mpiversion.mk
	@echo ">> Deleting Dynamically Generated Header Files <<"
	-@rm -f models/$(MODEL)/rhs_automatic.h
	-@rm -f models/$(MODEL)/amat_automatic.h
	-@rm -f models/$(MODEL)/aux_automatic.h
	-@rm -f algexpr2fort
	-@rm -f generate_code
cleandep:
	@echo ">> Deleting Dependency Files <<"
	-@rm -r $(DEPDIR)
	-@find . -name '*.d' -delete 2>/dev/null
test: particle_test nrt_unit
doc docs:
	-@rm -r doc/ # workaround for FORD bug
	ford jorek.md --no-search $(INCLUDES)



# Directories containing sources, ordered by number of files
DIRS := diagnostics				\
        diagnostics/tests			\
	models					\
	communication				\
	communication/IMAS			\
	communication/tests             	\
	grids/grid_utils			\
	grids/tests   				\
	solvers					\
	models/$(MODEL)				\
	refinement				\
	matrix					\
	particles				\
	particles/pushers			\
	particles/examples			\
	particles/diagnostics			\
	particles/tests				\
	particles/initialisers      \
	particles/postprocessors		\
	particles/postprocessors/spectra	\
	particles/postprocessors/lights		\
	particles/postprocessors/lens		\
	particles/postprocessors/filters	\
	particles/postprocessors/camera		\
	particles/postprocessors/examples	\
	particles/postprocessors/tests		\
	particles/postprocessors/utils		\
	particles/projection_functions		\
	particles/benchmarks/pusher_cartesian	\
	particles/benchmarks/pusher		\
	particles/benchmarks/projection		\
	elements				\
	elements/tests				\
	grids					\
	plots					\
	diagnostics/new_diag			\
	diagnostics/postproc			\
	tools					\
	tools/fruit				\
	tools/tests				\
	non_regression_tests/unit_tests		\
	datatypes				\
	benchmarks				\
	core					\
	core/tests                      	\
	.					\
	vacuum \
	dream_utilities

DIRS+=$(EXTRA_DIRS) # Specified in Makefile.inc or commandline

# All .f90 files we should generate .d dependency files for
depends:=$(basename $(notdir $(shell find $(DIRS) -maxdepth 1 -iname '*.f90')))
depends:=$(foreach dep,$(depends),$(DEPDIR)/$(dep).d)

# Check for multiple files with the same name in $(DIRS)
duplicates:
	@dups=`find $(DIRS) -maxdepth 1 -iname '*.f90' |\
	  xargs basename -s .f90 -a | sort | uniq -d`
	@if [[ -z "${dups// }" ]]; then echo "No duplicates detected"; \
	else echo "Duplicates found: ${dups}"; fi

printsettings:
	@echo "FC        = $(FC)"
	@echo "CC        = $(CC)"
	@echo "DEBUG     = $(DEBUG)"
	@echo "FLAGS     = $(FLAGS)"
	@echo "FFLAGS    = $(FFLAGS)"
	@echo "F90FLAGS  = $(F90FLAGS)"
	@echo "F77FLAGS  = $(F77FLAGS)"
	@echo "CFLAGS    = $(CFLAGS)"
	@echo "DEFINES   = $(DEFINES)"
	@echo "INCLUDES  = $(INCLUDES)"
	@echo "LIBS      = $(LIBS)"

$(OBJDIR)/mod_elt_matrix.o $(MODDIR)/mod_elt_matrix.mod: $(CGDEP)
$(OBJDIR)/mod_elt_matrix_fft.o $(MODDIR)/mod_elt_matrix_fft.mod: $(CGDEP)

# For each source dir add an explicit rule with the template
$(foreach dir,$(DIRS),$(eval $(call O_TEMPLATE,$(dir)/)))
# For each source dir add a rule to create dependency files
ifneq (cleanall,$(findstring cleanall,$(MAKECMDGOALS)))
  ifneq (cleandep,$(findstring cleandep,$(MAKECMDGOALS)))
    $(foreach dir,$(DIRS),$(eval $(call F90_D_TEMPLATE,$(dir)/)))
  endif
endif
# Include the dependency files that can be generated by the rules above
-include $(depends) # Make will build all of these and re-execute

# The included programs are defined in the $(depends) files
# For each of these programs add the default template
$(foreach prog,$(filter-out %kinetic_main,$(PROGRAM_SOURCES)),$(eval $(call PROGRAM_TEMPLATE,$(prog))))

# kinetic_main gets a custom link rule that filters MUSCLE3 stubs
MUSCLE3_STUBS := .obj/libmuscle.o .obj/ymmsl.o
.obj/libmuscle.o: ;
.obj/ymmsl.o: ;

kinetic_main: $(OBJDIR)/kinetic_main.o $(filter-out $(MUSCLE3_STUBS), \
              $(shell ./util/obj_deps $(DEPDIR)/kinetic_main.d))
	$(FC) $(FLAGS) $(EXTRA_FLAGS) $(DEFINES) $(INCLUDES) \
	    -o kinetic_main $^ $(LIBS)
# To compile all programs found in $(DIRS)
all: $(basename $(notdir $(PROGRAM_SOURCES)))
# A list of supported diagnostics, that should compile properly for regression
# testing to pass
most: jorek2_connection2 \
      jorek2_connection_stan \
      jorek2_connection_flux_aligned \
      jorek2_diagno \
      jorek2_diagno_spi \
      jorek2_fieldlines_vtk \
      jorek2_four \
      jorek2_IDS \
      CARIDDI_wall_curr \
      jorek2_poincare \
      jorek2_powers \
      jorek2_target2vtk \
      jorek2vtk_3d \
      jorek2vtk \
      jorek2vtk_GaussVortTerms \
      test_gvec2jorek_import \
      jorek_to_helena \
      new_diag_demo \
      jorek2_postproc \
      rst_bin2hdf5 \
      rst_hdf52bin \
      jorek2_main
# Make all object files we know of
find_files = $(wildcard $(dir)/*.f90) $(wildcard $(dir)/*.c) $(wildcard $(dir)/*.f) $(wildcard $(dir)/*.cpp)
objs: $(foreach file,$(foreach dir,$(DIRS), $(find_files)), $(OBJDIR)/$(notdir $(basename $(file))).o)

generate_code: algexpr2fort
	@echo ">> Generating evaluation statements for mod_elt_matrix <<"
	@./algexpr2fort
	@touch generate_code
algexpr2fort: LIBS=$(ALGEXPR_LIBS)
algexpr2fort: MUSCLE3_LIB=
algexpr2fort: LIBS := $(filter-out $(MUSCLE3_LIB), $(LIBS)) -lstdc++
# Special cases
# Add here: Global includes (as the line below)
INCLUDES += -Itools # for r3_info.h
INCLUDES += -Imodels
# C++ support
LIBS += -lstdc++ 
CXXFLAGS += -pedantic -Wall

# Rule-specific includes: an example
#jorek2_main: DEFINES+="-DMAIN "
eqdsk2jorek: LIBS+=$(LIBDIERCKX)

# Automatically download adas data for tungsten
particles/examples/%50_w.dat:
	wget http://open.adas.ac.uk/download/adf11/$*50/$*50_w.dat -O $@
compare_mc_coronal: | particles/examples/acd50_w.dat particles/examples/scd50_w.dat

# We need the MPI_VERSION variable for conditional compilation, but
# unfortunately Fortran defines it as an integer parameter, which
# we cannot use as a preprocessor symbol. To overcome this problem,
# we create a small program that prints out the value of the
# MPI_VERSION parameter and use this to add -DMPI_VERSION=X to FFLAGS.
mpiversion.mk:
	printf "include 'mpif.h'\nWRITE(*,fmt='(A22,I1)') 'FFLAGS+=-DMPI_VERSION=', MPI_VERSION\nEND" > $(OBJDIR)/mpi_version.f90
	($(FC) $(FLAGS) $(DEFINES) $(INCLUDES) -o $(OBJDIR)/mpi_version $(OBJDIR)/mpi_version.f90 $(LIBS) && $(OBJDIR)/mpi_version | tail -n1 > mpiversion.mk) || echo FFLAGS+=-DMPI_VERSION=0 > mpiversion.mk

-include mpiversion.mk
eqdsk2jorek: LIBS+=$(LIBDIERCKX)

# Is this used by anyone? Otherwise we could remove it
# It is not updated to this format yet.
-include forcheck.mk
